### ISSUE TITLE
Release of self-made datasets

### ISSUE THREAD

**Issue by Alchemistyui** [allenai/visprog#2]
Hi, thank you for your exciting work! I find that for the image editing and factual knowledge object tagging task, you annotate the evaluation dataset by yourself.
> To evaluate VISPROG on this task, we annotate 100 tagging instructions across 46 images
> To test VISPROG on the image editing instructions for de-identification, object highlighting, and object replacement, we collect 107 instructions across 65 images.

I'd like to ask if you have any plans to release them so that I can reproduce your results.
Thank you very much and looking forward to your reply.

**Comment by BigRedT** [comment]
@Alchemistyui, thanks for your interest in our work! I wish we could release those, but unfortunately, we won't be able to do so due to copyright restrictions.

**Comment by Alchemistyui** [comment]
@BigRedT Thank you very much for your reply! Then do you have any plan to release the sampled subset of GQA/NLVRv2 so that I can reproduce your result? Thank you in advance.
