### ISSUE TITLE
Using any Open-Source LLM

### ISSUE THREAD

**Issue by praeclarumjj3** [allenai/visprog#4]
Hi, thanks for your great pioneering work!

I had a couple of questions:
- I wonder if you tried using any of the many "free" open-source LLMs (LLaMA, MPT, etc.) during your experiments. If yes, how was the performance?
- Did you analyze the performance of program generation (for a query) v/s the PROMPTs you use? I am sorry if it's already mentioned in the paper and I missed it.

Thanks.

**Comment by BigRedT** [comment]
Hi @praeclarumjj3, glad you liked this work!

- When we were just getting started with this project (it's been a while :)), we looked into some of the open LLMs that were available at the time, but GPT3 seemed to work noticeably better. Haven't looked into the recent ones, but certainly worth a try!
- In the paper, we do show performance as a function of the number of in-context examples. Not sure if that is what you are asking for? Closing this for now, but feel free to re-open if that didn't answer your question.
